# Generated by Django 5.1.2 on 2024-10-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='Answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
        migrations.AlterModelTable(
            name='userquizattempt',
            table='UserQuizAttempt',
        ),
    ]
